project_id = "ooimkdueuozjfwadrkkh"

[functions.upload-to-langflow]
verify_jwt = true

[functions.ask-question]
verify_jwt = false

[functions.ask-question-csv]
verify_jwt = false

[functions.ask-question-bigquery]
verify_jwt = false

[functions.ask-question-google-sheets]
verify_jwt = false

[functions.ask-question-sql]
verify_jwt = false

[functions.bigquery-connect]
verify_jwt = true

[functions.list-bigquery-resources]
verify_jwt = true

[functions.list-google-sheets]
verify_jwt = true

[functions.google-sheets-connect]
verify_jwt = true

[functions.list-sql-tables]
verify_jwt = true

[functions.sql-database-connect]
verify_jwt = true