import React, { createContext, ReactNode, useContext, useState } from 'react';

export type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.account': 'Account',
    'nav.logout': 'Logout',
    'nav.getStarted': 'Get Started',
    'nav.tagline': 'Talk to your data',
    
    // Hero Section
    'hero.title': 'Turn your data into intelligent conversations',
    'hero.subtitle': 'Connect your data sources and ask questions in natural language. Get instant insights without complex queries.',
    'hero.getStarted': 'Get Started',
    'hero.howItWorks': 'How it works',
    
    // How it works
    'howItWorks.title': 'How it works',
    'howItWorks.step1.title': 'Connect your data',
    'howItWorks.step1.description': 'Upload CSV files, connect to BigQuery, or add other data sources',
    'howItWorks.step2.title': 'Ask questions',
    'howItWorks.step2.description': 'Use natural language to query your data',
    'howItWorks.step3.title': 'Get insights',
    'howItWorks.step3.description': 'Receive instant answers with charts and visualizations',
    'howItWorks.step4.title': 'Alerts',
    'howItWorks.step4.description': 'Create alerts to monitor metrics and receive notifications',
    
    // Benefits
    'benefits.title': 'Benefits',
    'benefits.easy.title': 'Easy to use',
    'benefits.easy.description': 'No need to learn SQL or complex query languages',
    'benefits.fast.title': 'Fast insights',
    'benefits.fast.description': 'Get answers in seconds, not hours',
    'benefits.secure.title': 'Secure',
    'benefits.secure.description': 'Your data remains private and secure',
    
    // Auth
    'auth.title': 'Access your account',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name',
    'auth.loginButton': 'Sign in',
    'auth.registerButton': 'Create account',
    'auth.loginError': 'Failed to sign in. Try again.',
    'auth.registerError': 'Failed to register. Try again.',
    'auth.registerSuccess': 'Registration successful! Check your email to confirm and then sign in.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.dataSources': 'Data Sources',
    'dashboard.connectedSources': 'connected source(s)',
    'dashboard.addSource': 'Configure Sources',
    'dashboard.agentConfig': 'Agent Configuration',
    'dashboard.agentConfigDesc': 'Add source details for the agent to understand the context.',
    'dashboard.configureAgent': 'Configure Agent',
    'dashboard.questionsAnswers': 'Questions & Answers',
    'dashboard.activeAgents': 'active agent(s)',
    'dashboard.newQuestion': 'New Question',
    'dashboard.alerts': 'Alerts',
    'dashboard.configuredAlerts': 'configured alert(s)',
    'dashboard.createAlert': 'Create Alert',
    'dashboard.channelConfig': 'Channel Configuration',
    'dashboard.channelConfigDesc': 'Configure which channels your agents will be available on.',
    'dashboard.configureChannels': 'Configure Channels',
    'dashboard.dataExplore': 'Data Explore',
    'dashboard.dataExploreDesc': 'Explore and analyze your data with interactive visualizations and insights.',
    'dashboard.autoML': 'Auto ML',
    'dashboard.autoMLDesc': 'Automatically build and deploy machine learning models from your data.',
    'dashboard.comingSoon': 'Coming Soon',
    
    // Sources
    'sources.title': 'Data Sources',
    'sources.filesTab': 'Files (CSV/XLSX)',
    'sources.bigQueryTab': 'Google BigQuery',
    'sources.uploadButton': 'Upload',
    'sources.uploading': 'Uploading...',
    'sources.connectBigQuery': 'Connect BigQuery',
    'sources.connecting': 'Connecting...',
    'sources.credentials': 'Credentials (JSON)',
    'sources.project': 'Project',
    'sources.dataset': 'Dataset',
    'sources.allowedTables': 'Allowed tables (comma separated)',
    'sources.projectPlaceholder': 'my-project',
    'sources.datasetPlaceholder': 'analytics',
    'sources.tablesPlaceholder': 'orders, customers',
    'sources.noSourcesFound': 'No data sources found. Upload CSV or XLSX files above.',
    'sources.deleteConfirm': 'Are you sure you want to delete this data source?',
    'sources.uploadError': 'Upload error:',
    'sources.selectCredentialsFile': 'Please select the JSON credentials file',
    'sources.fillRequiredFields': 'Please fill in all required fields',
    'sources.bigQueryConnected': 'BigQuery connected successfully! Source:',
    'sources.bigQueryError': 'Error connecting BigQuery:',
    'sources.unknownError': 'Unknown error',
    'sources.createdAt': 'Created at:',
    'sources.langflowIntegration': 'Langflow Integration',
    'sources.langflowName': 'Name in Langflow:',
    'sources.langflowPath': 'Path:',
    'sources.warning': 'Warning:',
    'sources.fileNotUploaded': 'File was not uploaded to Langflow',
    'sources.rows': 'Rows:',
    'sources.columns': 'Columns',
    'sources.firstRows': 'First rows:',
    'sources.size': 'Size:',
    'sources.connectedTables': 'Connected tables:',
    'sources.tablesNotFound': 'Tables not found:',
    'sources.removeFile': 'Remove',
    'sources.bigQueryInstructions': 'How to get your BigQuery credentials JSON file:',
    'sources.bigQueryStep1': '1. Go to Google Cloud Console',
    'sources.bigQueryStep2': '2. Navigate to APIs & Services > Credentials',
    'sources.bigQueryStep3': '3. Click "Create Credentials" > "Service Account"',
    'sources.bigQueryStep4': '4. Fill in the service account details and click "Create"',
    'sources.bigQueryStep5': '5. Click on the created service account',
    'sources.bigQueryStep6': '6. Go to "Keys" tab and click "Add Key" > "Create new key"',
    'sources.bigQueryStep7': '7. Select "JSON" format and download the file',
    'sources.bigQueryStep8': '8. Upload the downloaded JSON file above',
    'sources.bigQueryDocsLink': 'View official documentation',
    'sources.savedSourcesAppear': 'Saved sources will appear here',
    'sources.addSourcesInstructions': 'Click Add above to add PDFs, websites, text, videos or audio files. Or import a file directly from Google Drive.',
    
    // Agent
    'agent.title': 'Agent Configuration',
    'agent.name': 'Name',
    'agent.namePlaceholder': 'E.g.: Sales Analysis 2025',
    'agent.selectAgent': 'Select Agent',
    'agent.description': 'Description',
    'agent.descriptionPlaceholder': 'Describe what this agent should do...',
    'agent.dataSource': 'Data Source',
    'agent.selectDataSource': 'Select a data source',
    'agent.sharing': 'Sharing',
    'agent.enableSharing': 'Enable sharing',
    'agent.sharePassword': 'Share password',
    'agent.sharePasswordPlaceholder': 'Leave empty for no password',
    'agent.shareLink': 'Share link',
    'agent.copyLink': 'Copy link',
    'agent.linkCopied': 'Link copied!',
    'agent.suggestedQuestions': 'Suggested Questions',
    'agent.addQuestion': 'Add question',
    'agent.questionPlaceholder': 'Enter a suggested question...',
    'agent.save': 'Save',
    'agent.saving': 'Saving...',
    'agent.delete': 'Delete',
    'agent.deleting': 'Deleting...',
    'agent.deleteConfirm': 'Are you sure you want to delete the agent "{name}"? This action cannot be undone.',
    'agent.deleted': 'Agent deleted',
    'agent.deletedSuccess': 'Agent deleted successfully',
    'agent.error': 'Error',
    'agent.saved': 'Agent saved',
    'agent.savedSuccess': 'Agent saved successfully',
    'agent.createAgent': 'Create Agent',
    'agent.saveChanges': 'Save Changes',
    'agent.newAgent': 'New agent',
    'agent.noDataSourcesFound': 'No data sources found. Add sources first.',
    'agent.selectDataSourceHelp': 'Select the data source that this agent will have access to answer questions.',
    'agent.addSuggestedQuestionsHelp': 'Add questions that will appear as suggestions when someone uses this agent.',
    'agent.enableSharingHelp': 'Allows external people to access this agent',
    'agent.linkCopiedDescription': 'Shareable link copied to clipboard',
    'agent.passwordProtected': 'Password protected access',
    'agent.publicAccess': 'Public access - anyone with the link can access',
    'agent.passwordUpdated': 'Password updated',
    'agent.passwordUpdatedSuccess': 'Share password updated successfully',
    'agent.sharingEnabled': 'Sharing enabled',
    'agent.sharingDisabled': 'Sharing disabled',
    'agent.sharingEnabledSuccess': 'Shareable link created successfully',
    'agent.sharingDisabledSuccess': 'Shareable link removed',
    
    // Questions
    'questions.title': 'Questions',
    'questions.beforeStart': 'Before you start',
    'questions.createAgentFirst': 'Create an agent in "Briefing" to start asking questions.',
    'questions.agent': 'Agent',
    'questions.questionPlaceholder': 'Ex.: What is the revenue for the last 3 months by region?',
    'questions.ask': 'Ask',
    'questions.processing': 'Processing...',
    'questions.error': 'Error:',
    'questions.feedbackError': 'Error saving feedback:',
    'questions.suggestedQuestions': 'Suggested Questions',
    'questions.suggestedQuestionsLabel': 'Suggested Questions',
    'questions.clickToAsk': 'Click to ask',
    'questions.noSessions': 'No questions asked yet.',
    'questions.noQuestionsFound': 'No questions found yet.',
    'questions.processingQuestion': 'Processing your question...',
    'questions.question': 'Question',
    'questions.answerNotAvailable': 'Answer not available',
    'questions.analysisResult': 'Analysis Result',
    'questions.followUpQuestions': 'Follow-up Questions',
    'questions.positiveFeedbackLabel': 'Mark as positive feedback',
    'questions.negativeFeedbackLabel': 'Mark as negative feedback',
    'questions.deleteQuestionLabel': 'Delete question',
    'questions.deleteQuestionConfirm': 'Are you sure you want to delete this question?',
    'questions.status': 'Status',
    'questions.availableColumns': 'Available Columns',
    'questions.seoDescription': 'Ask questions in natural language',
    'questions.dateFormat': 'en-US',
    
    // Alerts
    'alerts.title': 'Alerts',
    'alerts.beforeStart': 'Before you start',
    'alerts.createAgentFirst': 'Create an agent in "Briefing" to start creating alerts.',
    'alerts.agent': 'Agent',
    'alerts.alertName': 'Alert Name',
    'alerts.question': 'Question',
    'alerts.email': 'Email',
    'alerts.emailPlaceholder': 'your@email.com',
    'alerts.frequency': 'Frequency',
    'alerts.daily': 'Daily',
    'alerts.weekly': 'Weekly',
    'alerts.monthly': 'Monthly',
    'alerts.executionTime': 'Execution Time',
    'alerts.dayOfWeek': 'Day of Week',
    'alerts.dayOfMonth': 'Day of Month',
    'alerts.monday': 'Monday',
    'alerts.tuesday': 'Tuesday',
    'alerts.wednesday': 'Wednesday',
    'alerts.thursday': 'Thursday',
    'alerts.friday': 'Friday',
    'alerts.saturday': 'Saturday',
    'alerts.sunday': 'Sunday',
    'alerts.createAlert': 'Create Alert',
    'alerts.creating': 'Creating...',
    'alerts.fillRequiredFields': 'Please fill in all required fields',
    'alerts.success': 'Success',
    'alerts.alertCreated': 'Alert created successfully!',
    'alerts.errorCreatingAlert': 'Error creating alert',
    'alerts.error': 'Error',
    'alerts.noAlerts': 'No alerts configured yet.',
    'alerts.deleteConfirm': 'Are you sure you want to delete this alert?',
    'alerts.deleted': 'Alert deleted',
    'alerts.deletedSuccess': 'Alert deleted successfully',
    'alerts.newAlert': 'New Alert',
    'alerts.alertNameLabel': 'Alert Name',
    'alerts.alertNamePlaceholder': 'Alert name',
    'alerts.agentLabel': 'Agent',
    'alerts.selectAgentPlaceholder': 'Select an agent',
    'alerts.emailLabel': 'Email for notification',
    'alerts.questionLabel': 'Question/Query',
    'alerts.questionPlaceholder': 'What question or condition to monitor?',
    'alerts.frequencyLabel': 'Frequency',
    'alerts.executionTimeLabel': 'Execution Time',
    'alerts.dayOfWeekLabel': 'Day of Week',
    'alerts.dayOfMonthLabel': 'Day of Month',
    'alerts.noAlertsConfigured': 'No alerts configured. Create your first alert above.',
    'alerts.remove': 'Remove',
    'alerts.questionField': 'Question:',
    'alerts.emailField': 'Email:',
    'alerts.scheduleField': 'Schedule:',
    'alerts.at': 'at',
    'alerts.day': 'Day',
    'alerts.createdAt': 'Created at:',
    'alerts.nextExecution': 'Next execution:',
    'alerts.alertRemoved': 'Alert removed',
    
    // Account
    'account.title': 'Account',
    'account.export': 'Export',
    'account.exportHistory': 'Export History',
    'account.security': 'Security',
    'account.deleteAccount': 'Delete Account and Data',
    'account.deleteConfirm': 'Are you sure you want to delete your account and local data?',
    
    // Footer
    'footer.copyright': '© {year} Talk to your data. All rights reserved.',
    
         // Channels
     'channels.title': 'Channels',
     'channels.subtitle': 'Connect and manage your communication channels to streamline customer interactions',
     'channels.whatsapp.name': 'WhatsApp',
     'channels.whatsapp.description': 'Connect your WhatsApp Business API to receive and respond to messages',
     'channels.slack.name': 'Slack',
     'channels.slack.description': 'Integrate with Slack to manage conversations and notifications',
     'channels.telegram.name': 'Telegram',
     'channels.telegram.description': 'Connect Telegram bot for automated customer support',
     'channels.comingSoon': 'Coming Soon',
     'channels.available': 'Available',
     'channels.connectWhatsApp': 'Connect WhatsApp',
     'channels.connectSlack': 'Connect Slack',
     'channels.connectTelegram': 'Connect Telegram',
     'channels.connecting': 'Connecting...',
     'channels.connected': 'Connected',
     'channels.needMoreIntegrations.title': 'Need More Integrations?',
     'channels.needMoreIntegrations.description': 'We\'re constantly adding new channel integrations. Contact our support team to request specific platforms.',
     'channels.requestIntegration': 'Request Integration',
     
     // Pricing
     'pricing.title': 'Pricing',
     'pricing.subtitle': 'Choose the plan that best fits your needs',
           'pricing.free.title': 'Free',
      'pricing.free.price': '$0',
      'pricing.free.period': '/month',
      'pricing.free.description': 'Perfect for getting started',
      'pricing.free.button': 'Get Started',
                       'pricing.pro.title': 'Pro',
       'pricing.pro.price': '$199',
       'pricing.pro.period': '/month',
      'pricing.pro.description': 'Ideal for growing teams',
      'pricing.pro.button': 'Start Pro Trial',
           'pricing.enterprise.title': 'Enterprise',
      'pricing.enterprise.price': 'Custom',
      'pricing.enterprise.period': '',
      'pricing.enterprise.description': 'For large organizations',
      'pricing.enterprise.button': 'Contact Sales',
     'pricing.features': 'Features',
     'pricing.mostPopular': 'Most Popular',
     'pricing.billedAnnually': 'Billed annually',
     'pricing.billedMonthly': 'Billed monthly',
     'pricing.save20': 'Save 20%',
     'pricing.needCustom': 'Need something custom?',
     'pricing.contactUs': 'Contact us',
     
     // Settings
     'settings.title': 'Settings',
     'settings.manageSubscription': 'Manage subscription',
     'settings.language': 'Language',
     
     // Add Source Modal
     'addSource.title': 'Add sources',
     'addSource.description': 'Sources allow NotebookLM to base its answers on the most important information for you.',
     'addSource.examples': '(Examples: marketing plans, course readings, research notes, meeting transcripts, sales documents, etc.)',
     'addSource.uploadTab': 'Upload',
     'addSource.bigQueryTab': 'BigQuery',
     'addSource.sheetsTab': 'Google Sheets',
     'addSource.uploadTitle': 'Upload sources',
     'addSource.dragDrop': 'Drag and drop or',
     'addSource.chooseFile': 'choose file',
     'addSource.uploadText': 'for upload',
     'addSource.supportedTypes': 'Supported file types: PDF, txt, Markdown, Audio (e.g. mp3), CSV, XLSX',
     'addSource.credentials': 'Credentials (JSON)',
     'addSource.project': 'Project',
     'addSource.dataset': 'Dataset',
     'addSource.allowedTables': 'Allowed tables (comma separated)',
     'addSource.projectPlaceholder': 'my-project',
     'addSource.datasetPlaceholder': 'analytics',
     'addSource.tablesPlaceholder': 'orders, customers',
     'addSource.connectBigQuery': 'Connect BigQuery',
     'addSource.sheetsUrl': 'Google Sheets link',
     'addSource.sheetsUrlPlaceholder': 'https://docs.google.com/spreadsheets/d/...',
     'addSource.sheetsDescription': 'Paste the sharing link of the Google Sheets you want to connect',
     'addSource.connectSheets': 'Connect Google Sheets',
      'addSource.sourceLimit': 'Source limit',
      'addSource.filesUploaded': 'Files uploaded successfully!',
      'addSource.uploadError': 'Error uploading files',
      
      // Notebook
      'notebook.chat': 'Chat',
      'notebook.addSourceToStart': 'Add a source to get started',
      'notebook.addSourceDescription': 'Upload documents, connect to BigQuery, or add Google Sheets to start asking questions about your data.',
      'notebook.uploadSource': 'Upload a source',
      'notebook.inputPlaceholder': 'Upload a source to get started',
      
      // Studio
      'studio.audioOverview': 'Audio Overview',
      'studio.autoML': 'Auto ML',
      'studio.reports': 'Reports',
      'studio.alertConfig': 'Alert Configuration',
      'studio.connectWhatsApp': 'Connect to WhatsApp',
      'studio.connectSlack': 'Connect to Slack',
      'studio.connections': 'Connections',
      'studio.outputDescription': 'Studio output will be saved here. After adding sources, click to add Audio Overview, Study Guide, Mind Map and more!',
      'studio.addNote': 'Add note',
      'studio.comingSoon': 'Coming soon',
      'studio.comingSoonDescription': 'This feature will be available soon.',
   },
  pt: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.account': 'Conta',
    'nav.logout': 'Sair',
    'nav.getStarted': 'Começar agora',
    'nav.tagline': 'Converse com seus dados',
    
    // Hero Section
    'hero.title': 'Transforme seus dados em conversas inteligentes',
    'hero.subtitle': 'Conecte suas fontes de dados e faça perguntas em linguagem natural. Obtenha insights instantâneos sem consultas complexas.',
    'hero.getStarted': 'Começar agora',
    'hero.howItWorks': 'Como funciona',
    
    // How it works
    'howItWorks.title': 'Como funciona',
    'howItWorks.step1.title': 'Conecte seus dados',
    'howItWorks.step1.description': 'Carregue arquivos CSV, conecte ao BigQuery ou adicione outras fontes de dados',
    'howItWorks.step2.title': 'Faça perguntas',
    'howItWorks.step2.description': 'Use linguagem natural para consultar seus dados',
    'howItWorks.step3.title': 'Obtenha insights',
    'howItWorks.step3.description': 'Receba respostas instantâneas com gráficos e visualizações',
    'howItWorks.step4.title': 'Alertas',
    'howItWorks.step4.description': 'Crie alertas para monitorar métricas e receber notificações',
    
    // Benefits
    'benefits.title': 'Benefícios',
    'benefits.easy.title': 'Fácil de usar',
    'benefits.easy.description': 'Não é necessário aprender SQL ou linguagens de consulta complexas',
    'benefits.fast.title': 'Insights rápidos',
    'benefits.fast.description': 'Obtenha respostas em segundos, não em horas',
    'benefits.secure.title': 'Seguro',
    'benefits.secure.description': 'Seus dados permanecem privados e seguros',
    
    // Auth
    'auth.title': 'Acessar sua conta',
    'auth.login': 'Login',
    'auth.register': 'Registrar',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.name': 'Nome',
    'auth.loginButton': 'Entrar',
    'auth.registerButton': 'Criar conta',
    'auth.loginError': 'Falha ao entrar. Tente novamente.',
    'auth.registerError': 'Falha ao registrar. Tente novamente.',
    'auth.registerSuccess': 'Cadastro realizado! Verifique seu e-mail para confirmar e então faça login.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.dataSources': 'Fontes de Dados',
    'dashboard.connectedSources': 'fonte(s) conectada(s)',
    'dashboard.addSource': 'Configurar Fontes',
    'dashboard.agentConfig': 'Configuração do Agente',
    'dashboard.agentConfigDesc': 'Adicione o detalhamento das fontes para o agente entender o contexto.',
    'dashboard.configureAgent': 'Configurar Agente',
    'dashboard.questionsAnswers': 'Perguntas & Respostas',
    'dashboard.activeAgents': 'agente(s) ativo(s)',
    'dashboard.newQuestion': 'Nova Pergunta',
    'dashboard.alerts': 'Alertas',
    'dashboard.configuredAlerts': 'alerta(s) configurado(s)',
    'dashboard.createAlert': 'Criar Alerta',
    'dashboard.channelConfig': 'Configuração de Canais',
    'dashboard.channelConfigDesc': 'Configure em quais canais seus agentes estarão disponíveis.',
    'dashboard.configureChannels': 'Configurar Canais',
    'dashboard.dataExplore': 'Exploração de Dados',
    'dashboard.dataExploreDesc': 'Explore e analise seus dados com visualizações interativas e insights.',
    'dashboard.autoML': 'Auto ML',
    'dashboard.autoMLDesc': 'Construa e implante automaticamente modelos de machine learning a partir dos seus dados.',
    'dashboard.comingSoon': 'Em Breve',
    
    // Sources
    'sources.title': 'Fontes de Dados',
    'sources.filesTab': 'Arquivos (CSV/XLSX)',
    'sources.bigQueryTab': 'Google BigQuery',
    'sources.uploadButton': 'Fazer upload',
    'sources.uploading': 'Enviando...',
    'sources.connectBigQuery': 'Conectar BigQuery',
    'sources.connecting': 'Conectando...',
    'sources.credentials': 'Credenciais (JSON)',
    'sources.project': 'Projeto',
    'sources.dataset': 'Dataset',
    'sources.allowedTables': 'Tabelas permitidas (separadas por vírgula)',
    'sources.projectPlaceholder': 'meu-projeto',
    'sources.datasetPlaceholder': 'analytics',
    'sources.tablesPlaceholder': 'orders, customers',
    'sources.noSourcesFound': 'Nenhuma fonte de dados encontrada. Faça upload de arquivos CSV ou XLSX acima.',
    'sources.deleteConfirm': 'Tem certeza que deseja deletar esta fonte de dados?',
    'sources.uploadError': 'Erro no upload:',
    'sources.selectCredentialsFile': 'Por favor, selecione o arquivo de credenciais JSON',
    'sources.fillRequiredFields': 'Por favor, preencha todos os campos obrigatórios',
    'sources.bigQueryConnected': 'BigQuery conectado com sucesso! Fonte:',
    'sources.bigQueryError': 'Erro ao conectar BigQuery:',
    'sources.unknownError': 'Erro desconhecido',
    'sources.createdAt': 'Criado em:',
    'sources.langflowIntegration': 'Integração Langflow',
    'sources.langflowName': 'Nome no Langflow:',
    'sources.langflowPath': 'Caminho:',
    'sources.warning': 'Aviso:',
    'sources.fileNotUploaded': 'Arquivo não foi carregado no Langflow',
    'sources.rows': 'Linhas:',
    'sources.columns': 'Colunas',
    'sources.firstRows': 'Primeiras linhas:',
    'sources.size': 'Tamanho:',
    'sources.connectedTables': 'Tabelas conectadas:',
    'sources.tablesNotFound': 'Tabelas não encontradas:',
    'sources.removeFile': 'Remover',
    'sources.bigQueryInstructions': 'Como obter seu arquivo JSON de credenciais do BigQuery:',
    'sources.bigQueryStep1': '1. Acesse o Google Cloud Console',
    'sources.bigQueryStep2': '2. Navegue para APIs e Serviços > Credenciais',
    'sources.bigQueryStep3': '3. Clique em "Criar Credenciais" > "Conta de Serviço"',
    'sources.bigQueryStep4': '4. Preencha os detalhes da conta de serviço e clique em "Criar"',
    'sources.bigQueryStep5': '5. Clique na conta de serviço criada',
    'sources.bigQueryStep6': '6. Vá para a aba "Chaves" e clique em "Adicionar Chave" > "Criar nova chave"',
    'sources.bigQueryStep7': '7. Selecione o formato "JSON" e baixe o arquivo',
    'sources.bigQueryStep8': '8. Faça upload do arquivo JSON baixado acima',
    'sources.bigQueryDocsLink': 'Ver documentação oficial',
    'sources.savedSourcesAppear': 'As fontes salvas aparecerão aqui',
    'sources.addSourcesInstructions': 'Clique em Add acima para adicionar PDFs, websites, texto, vídeos ou arquivos de áudio. Ou importe um arquivo diretamente do Google Drive.',
    
    // Agent
    'agent.title': 'Configuração do Agente',
    'agent.name': 'Nome',
    'agent.namePlaceholder': 'Ex.: Análises de Vendas 2025',
    'agent.selectAgent': 'Selecionar Agente',
    'agent.description': 'Descrição',
    'agent.descriptionPlaceholder': 'Descreva o que este agente deve fazer...',
    'agent.dataSource': 'Fonte de Dados',
    'agent.selectDataSource': 'Selecione uma fonte de dados',
    'agent.sharing': 'Compartilhamento',
    'agent.enableSharing': 'Habilitar compartilhamento',
    'agent.sharePassword': 'Senha de compartilhamento',
    'agent.sharePasswordPlaceholder': 'Deixe vazio para sem senha',
    'agent.shareLink': 'Link de compartilhamento',
    'agent.copyLink': 'Copiar link',
    'agent.linkCopied': 'Link copiado!',
    'agent.suggestedQuestions': 'Perguntas Sugeridas',
    'agent.addQuestion': 'Adicionar pergunta',
    'agent.questionPlaceholder': 'Digite uma pergunta sugerida...',
    'agent.save': 'Salvar',
    'agent.saving': 'Salvando...',
    'agent.delete': 'Deletar',
    'agent.deleting': 'Deletando...',
    'agent.deleteConfirm': 'Tem certeza que deseja deletar o agente "{name}"? Esta ação não pode ser desfeita.',
    'agent.deleted': 'Agente deletado',
    'agent.deletedSuccess': 'Agente deletado com sucesso',
    'agent.error': 'Erro',
    'agent.saved': 'Agente salvo',
    'agent.savedSuccess': 'Agente salvo com sucesso',
    'agent.createAgent': 'Criar Agente',
    'agent.saveChanges': 'Salvar Alterações',
    'agent.newAgent': 'Novo agente',
    'agent.noDataSourcesFound': 'Nenhuma fonte de dados encontrada. Adicione fontes primeiro.',
    'agent.selectDataSourceHelp': 'Selecione a fonte de dados que este agente terá acesso para responder perguntas.',
    'agent.addSuggestedQuestionsHelp': 'Adicione perguntas que aparecerão como sugestões quando alguém usar este agente.',
    'agent.enableSharingHelp': 'Permite que pessoas externas acessem este agente',
    'agent.linkCopiedDescription': 'Link compartilhável copiado para a área de transferência',
    'agent.passwordProtected': 'Acesso protegido por senha',
    'agent.publicAccess': 'Acesso público - qualquer pessoa com o link pode acessar',
    'agent.passwordUpdated': 'Senha atualizada',
    'agent.passwordUpdatedSuccess': 'Senha de compartilhamento atualizada com sucesso',
    'agent.sharingEnabled': 'Compartilhamento ativado',
    'agent.sharingDisabled': 'Compartilhamento desativado',
    'agent.sharingEnabledSuccess': 'Link compartilhável criado com sucesso',
    'agent.sharingDisabledSuccess': 'Link compartilhável removido',
    
    // Questions
    'questions.title': 'Perguntas',
    'questions.beforeStart': 'Antes de começar',
    'questions.createAgentFirst': 'Crie um agente em "Briefing" para começar a perguntar.',
    'questions.agent': 'Agente',
    'questions.questionPlaceholder': 'Ex.: Qual a receita dos últimos 3 meses por região?',
    'questions.ask': 'Perguntar',
    'questions.processing': 'Processando...',
    'questions.error': 'Erro:',
    'questions.feedbackError': 'Erro ao salvar feedback:',
    'questions.suggestedQuestions': 'Perguntas Sugeridas',
    'questions.suggestedQuestionsLabel': 'Perguntas Sugeridas',
    'questions.clickToAsk': 'Clique para perguntar',
    'questions.noSessions': 'Nenhuma pergunta feita ainda.',
    'questions.noQuestionsFound': 'Nenhuma pergunta encontrada ainda.',
    'questions.processingQuestion': 'Processando sua pergunta...',
    'questions.question': 'Pergunta',
    'questions.answerNotAvailable': 'Resposta não disponível',
    'questions.analysisResult': 'Resultado da Análise',
    'questions.followUpQuestions': 'Perguntas de Acompanhamento',
    'questions.positiveFeedbackLabel': 'Marcar como feedback positivo',
    'questions.negativeFeedbackLabel': 'Marcar como feedback negativo',
    'questions.deleteQuestionLabel': 'Deletar pergunta',
    'questions.deleteQuestionConfirm': 'Tem certeza que deseja deletar esta pergunta?',
    'questions.status': 'Status',
    'questions.availableColumns': 'Colunas disponíveis',
    'questions.seoDescription': 'Faça perguntas em linguagem natural',
    'questions.dateFormat': 'pt-BR',
    
    // Alerts
    'alerts.title': 'Alertas',
    'alerts.beforeStart': 'Antes de começar',
    'alerts.createAgentFirst': 'Crie um agente em "Briefing" para começar a criar alertas.',
    'alerts.agent': 'Agente',
    'alerts.alertName': 'Nome do Alerta',
    'alerts.question': 'Pergunta',
    'alerts.email': 'E-mail',
    'alerts.emailPlaceholder': 'seu@email.com',
    'alerts.frequency': 'Frequência',
    'alerts.daily': 'Diário',
    'alerts.weekly': 'Semanal',
    'alerts.monthly': 'Mensal',
    'alerts.executionTime': 'Horário de Execução',
    'alerts.dayOfWeek': 'Dia da Semana',
    'alerts.dayOfMonth': 'Dia do Mês',
    'alerts.monday': 'Segunda-feira',
    'alerts.tuesday': 'Terça-feira',
    'alerts.wednesday': 'Quarta-feira',
    'alerts.thursday': 'Quinta-feira',
    'alerts.friday': 'Sexta-feira',
    'alerts.saturday': 'Sábado',
    'alerts.sunday': 'Domingo',
    'alerts.createAlert': 'Criar Alerta',
    'alerts.creating': 'Criando...',
    'alerts.fillRequiredFields': 'Preencha todos os campos obrigatórios',
    'alerts.success': 'Sucesso',
    'alerts.alertCreated': 'Alerta criado com sucesso!',
    'alerts.errorCreatingAlert': 'Erro ao criar alerta',
    'alerts.error': 'Erro',
    'alerts.noAlerts': 'Nenhum alerta configurado ainda.',
    'alerts.deleteConfirm': 'Tem certeza que deseja deletar este alerta?',
    'alerts.deleted': 'Alerta deletado',
    'alerts.deletedSuccess': 'Alerta deletado com sucesso',
    'alerts.newAlert': 'Novo Alerta',
    'alerts.alertNameLabel': 'Nome do Alerta',
    'alerts.alertNamePlaceholder': 'Nome do alerta',
    'alerts.agentLabel': 'Agente',
    'alerts.selectAgentPlaceholder': 'Selecione um agente',
    'alerts.emailLabel': 'E-mail para notificação',
    'alerts.questionLabel': 'Pergunta/Query',
    'alerts.questionPlaceholder': 'Qual pergunta ou condição monitorar?',
    'alerts.frequencyLabel': 'Frequência',
    'alerts.executionTimeLabel': 'Horário de Execução',
    'alerts.dayOfWeekLabel': 'Dia da Semana',
    'alerts.dayOfMonthLabel': 'Dia do Mês',
    'alerts.noAlertsConfigured': 'Nenhum alerta configurado. Crie seu primeiro alerta acima.',
    'alerts.remove': 'Remover',
    'alerts.questionField': 'Pergunta:',
    'alerts.emailField': 'Email:',
    'alerts.scheduleField': 'Agendamento:',
    'alerts.at': 'às',
    'alerts.day': 'Dia',
    'alerts.createdAt': 'Criado em:',
    'alerts.nextExecution': 'Próxima execução:',
    'alerts.alertRemoved': 'Alerta removido',
    
    // Account
    'account.title': 'Conta',
    'account.export': 'Exportação',
    'account.exportHistory': 'Exportar histórico',
    'account.security': 'Segurança',
    'account.deleteAccount': 'Excluir conta e dados',
    'account.deleteConfirm': 'Tem certeza que deseja excluir sua conta e dados locais?',
    
    // Footer
    'footer.copyright': '© {year} Converse com seus dados. Todos os direitos reservados.',
    
         // Channels
     'channels.title': 'Canais',
     'channels.subtitle': 'Conecte e gerencie seus canais de comunicação para otimizar as interações com clientes',
     'channels.whatsapp.name': 'WhatsApp',
     'channels.whatsapp.description': 'Conecte sua API do WhatsApp Business para receber e responder mensagens',
     'channels.slack.name': 'Slack',
     'channels.slack.description': 'Integre com o Slack para gerenciar conversas e notificações',
     'channels.telegram.name': 'Telegram',
     'channels.telegram.description': 'Conecte bot do Telegram para suporte automatizado ao cliente',
     'channels.comingSoon': 'Em Breve',
     'channels.available': 'Disponível',
     'channels.connectWhatsApp': 'Conectar WhatsApp',
     'channels.connectSlack': 'Conectar Slack',
     'channels.connectTelegram': 'Conectar Telegram',
     'channels.connecting': 'Conectando...',
     'channels.connected': 'Conectado',
     'channels.needMoreIntegrations.title': 'Precisa de Mais Integrações?',
     'channels.needMoreIntegrations.description': 'Estamos constantemente adicionando novas integrações de canais. Entre em contato com nossa equipe de suporte para solicitar plataformas específicas.',
     'channels.requestIntegration': 'Solicitar Integração',
     
     // Pricing
     'pricing.title': 'Preços',
     'pricing.subtitle': 'Escolha o plano que melhor atende às suas necessidades',
           'pricing.free.title': 'Grátis',
      'pricing.free.price': 'R$0',
      'pricing.free.period': '/mês',
      'pricing.free.description': 'Perfeito para começar',
      'pricing.free.button': 'Começar Agora',
                       'pricing.pro.title': 'Pro',
       'pricing.pro.price': 'R$199',
       'pricing.pro.period': '/mês',
      'pricing.pro.description': 'Ideal para equipes em crescimento',
      'pricing.pro.button': 'Iniciar Teste Pro',
           'pricing.enterprise.title': 'Empresarial',
      'pricing.enterprise.price': 'Personalizado',
      'pricing.enterprise.period': '',
      'pricing.enterprise.description': 'Para grandes organizações',
      'pricing.enterprise.button': 'Falar com Vendas',
     'pricing.features': 'Recursos',
     'pricing.mostPopular': 'Mais Popular',
     'pricing.billedAnnually': 'Cobrado anualmente',
     'pricing.billedMonthly': 'Cobrado mensalmente',
     'pricing.save20': 'Economize 20%',
     'pricing.needCustom': 'Precisa de algo personalizado?',
     'pricing.contactUs': 'Entre em contato conosco',
     
     // Settings
     'settings.title': 'Configurações',
     'settings.manageSubscription': 'Gerenciar inscrição',
     'settings.language': 'Idioma',
     
     // Add Source Modal
     'addSource.title': 'Adicionar fontes',
     'addSource.description': 'As fontes permitem que o NotebookLM baseie suas respostas nas informações mais importantes para você.',
     'addSource.examples': '(Exemplos: planos de marketing, leitura de curso, notas de pesquisa, transcrições de reunião, documentos de vendas, etc.)',
     'addSource.uploadTab': 'Upload',
     'addSource.bigQueryTab': 'BigQuery',
     'addSource.sheetsTab': 'Google Sheets',
     'addSource.uploadTitle': 'Upload de fontes',
     'addSource.dragDrop': 'Arraste e solte ou',
     'addSource.chooseFile': 'escolha arquivo',
     'addSource.uploadText': 'para upload',
     'addSource.supportedTypes': 'Tipos de arquivo suportados: PDF, txt, Markdown, Audio (e.g. mp3), CSV, XLSX',
     'addSource.credentials': 'Credenciais (JSON)',
     'addSource.project': 'Projeto',
     'addSource.dataset': 'Dataset',
     'addSource.allowedTables': 'Tabelas permitidas (separadas por vírgula)',
     'addSource.projectPlaceholder': 'meu-projeto',
     'addSource.datasetPlaceholder': 'analytics',
     'addSource.tablesPlaceholder': 'orders, customers',
     'addSource.connectBigQuery': 'Conectar BigQuery',
     'addSource.sheetsUrl': 'Link do Google Sheets',
     'addSource.sheetsUrlPlaceholder': 'https://docs.google.com/spreadsheets/d/...',
     'addSource.sheetsDescription': 'Cole o link de compartilhamento do Google Sheets que você deseja conectar',
     'addSource.connectSheets': 'Conectar Google Sheets',
      'addSource.sourceLimit': 'Limite de fontes',
      'addSource.filesUploaded': 'Arquivos enviados com sucesso!',
      'addSource.uploadError': 'Erro ao enviar arquivos',
      
      // Notebook
      'notebook.chat': 'Chat',
      'notebook.addSourceToStart': 'Adicione uma fonte para começar',
      'notebook.addSourceDescription': 'Carregue documentos, conecte ao BigQuery ou adicione Google Sheets para começar a fazer perguntas aos seus dados.',
      'notebook.uploadSource': 'Fazer upload de uma fonte',
      'notebook.inputPlaceholder': 'Fazer upload de uma fonte para começar',
      
      // Studio
      'studio.audioOverview': 'Visão Geral de Áudio',
      'studio.autoML': 'Auto ML',
      'studio.reports': 'Relatórios',
      'studio.alertConfig': 'Configuração de Alertas',
      'studio.connectWhatsApp': 'Conectar ao WhatsApp',
      'studio.connectSlack': 'Conectar ao Slack',
      'studio.connections': 'Conexões',
      'studio.outputDescription': 'A saída do Studio será salva aqui. Após adicionar fontes, clique para adicionar Visão Geral de Áudio, Guia de Estudo, Mapa Mental e mais!',
      'studio.addNote': 'Adicionar nota',
      'studio.comingSoon': 'Recurso em breve',
      'studio.comingSoonDescription': 'Esta funcionalidade estará disponível em breve.',
   }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Try to get the saved language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage && (savedLanguage === 'en' || savedLanguage === 'pt') ? savedLanguage : 'en';
  });

  const t = (key: string, params?: Record<string, any>): string => {
    let text = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        text = text.replace(new RegExp(`{${param}}`, 'g'), String(value));
      });
    }
    
    return text;
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};