import React, { createContext, ReactNode, useContext, useState } from 'react';

export type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Common
    'common.loading': 'Loading...',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.account': 'Account',
    'nav.logout': 'Logout',
    'nav.getStarted': 'Get Started',
    'nav.tagline': 'Talk to your data',
    
    // Hero Section
    'hero.title': 'Turn your data into intelligent conversations',
    'hero.subtitle': 'Connect your data sources and ask questions in natural language. Get instant insights without complex queries.',
    'hero.getStarted': 'Get Started',
    'hero.howItWorks': 'How it works',
    
    // How it works
    'howItWorks.title': 'How it works',
    'howItWorks.step1.title': 'Connect your data',
    'howItWorks.step1.description': 'Upload CSV files, connect to BigQuery, or add other data sources',
    'howItWorks.step2.title': 'Ask questions',
    'howItWorks.step2.description': 'Use natural language to query your data',
    'howItWorks.step3.title': 'Get insights',
    'howItWorks.step3.description': 'Receive instant answers with charts and visualizations',
    'howItWorks.step4.title': 'Alerts',
    'howItWorks.step4.description': 'Create alerts to monitor metrics and receive notifications',
    
    // Benefits
    'benefits.title': 'Benefits',
    'benefits.easy.title': 'Easy to use',
    'benefits.easy.description': 'No need to learn SQL or complex query languages',
    'benefits.easy.extended': 'Ask questions in natural language and get insights without writing complex queries.',
    'benefits.easy.tagline': 'Simplified data analysis.',
    'benefits.fast.title': 'Fast insights',
    'benefits.fast.description': 'Get answers in seconds, not hours',
    'benefits.fast.extended': 'Connect your data sources and start asking questions immediately to get instant answers.',
    'benefits.fast.tagline': 'Make decisions with agility.',
    'benefits.secure.title': 'Secure',
    'benefits.secure.description': 'Your data remains private and secure',
    'benefits.secure.extended': 'Your data is encrypted and you maintain full control over who can access it.',
    'benefits.secure.tagline': 'Privacy guaranteed.',
    
    // Testimonials
    'testimonials.title': 'What people are saying',
    'testimonials.feedback1': 'Finally a tool that understands I don\'t speak SQL. I just ask in plain English and it answers. Amazing!',
    'testimonials.name1': 'John Developer',
    'testimonials.role1': 'Former Excel Slave',
    'testimonials.feedback2': 'Saved hours trying to understand complex dashboards. Now I just ask "how much did we sell this month?" and done.',
    'testimonials.name2': 'Mary Smith',
    'testimonials.role2': 'CEO of Something',
    'testimonials.feedback3': 'Connected my BigQuery and now I talk to billions of rows like it\'s a chat. My reports come out in seconds.',
    'testimonials.name3': 'Peter Costa',
    'testimonials.role3': 'Unicorn Startup Founder',
    
    // Auth
    'auth.title': 'Access your account',
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name',
    'auth.loginButton': 'Sign in',
    'auth.registerButton': 'Create account',
    'auth.loginError': 'Failed to sign in. Try again.',
    'auth.registerError': 'Failed to register. Try again.',
    'auth.registerSuccess': 'Registration successful! Check your email to confirm and then sign in.',
    'auth.forgotPassword': 'Forgot password?',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subscription': 'Manage subscription',
    'settings.users': 'Users',
    'settings.workspaceAccess': 'Access Control',
    'settings.language': 'Language',
    'settings.logout': 'Logout',
    'settings.newWorkspace': 'New workspace',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.dataSources': 'Data Sources',
    'dashboard.connectedSources': 'connected source(s)',
    'dashboard.addSource': 'Configure Sources',
    'dashboard.agentConfig': 'Agent Configuration',
    'dashboard.agentConfigDesc': 'Add source details for the agent to understand the context.',
    'dashboard.configureAgent': 'Configure Agent',
    'dashboard.questionsAnswers': 'Questions & Answers',
    'dashboard.activeAgents': 'active agent(s)',
    'dashboard.newQuestion': 'New Question',
    'dashboard.alerts': 'Alerts',
    'dashboard.configuredAlerts': 'configured alert(s)',
    'dashboard.createAlert': 'Create Alert',
    'dashboard.channelConfig': 'Channel Configuration',
    'dashboard.channelConfigDesc': 'Configure which channels your agents will be available on.',
    'dashboard.configureChannels': 'Configure Channels',
    'dashboard.dataExplore': 'Data Explore',
    'dashboard.dataExploreDesc': 'Explore and analyze your data with interactive visualizations and insights.',
    'dashboard.autoML': 'Auto ML',
    'dashboard.autoMLDesc': 'Automatically build and deploy machine learning models from your data.',
    'dashboard.comingSoon': 'Coming Soon',
    
    // Sources
    'sources.title': 'Sources',
    'sources.add': 'Add',
    'sources.filesTab': 'Files (CSV/XLSX)',
    'sources.bigQueryTab': 'Google BigQuery',
    'sources.uploadButton': 'Upload',
    'sources.uploading': 'Uploading...',
    'sources.connectBigQuery': 'Connect BigQuery',
    'sources.connecting': 'Connecting...',
    'sources.credentials': 'Credentials (JSON)',
    'sources.project': 'Project',
    'sources.dataset': 'Dataset',
    'sources.allowedTables': 'Allowed tables (comma separated)',
    'sources.projectPlaceholder': 'my-project',
    'sources.datasetPlaceholder': 'analytics',
    'sources.tablesPlaceholder': 'orders, customers',
    'sources.noSourcesFound': 'No data sources found. Upload CSV or XLSX files above.',
    'sources.deleteConfirm': 'Are you sure you want to delete this data source?',
    'sources.uploadError': 'Upload error:',
    'sources.selectCredentialsFile': 'Please select the JSON credentials file',
    'sources.fillRequiredFields': 'Please fill in all required fields',
    'sources.bigQueryConnected': 'BigQuery connected successfully! Source:',
    'sources.bigQueryError': 'Error connecting BigQuery:',
    'sources.unknownError': 'Unknown error',
    'sources.createdAt': 'Created at:',
    'sources.langflowIntegration': 'Langflow Integration',
    'sources.langflowName': 'Name in Langflow:',
    'sources.langflowPath': 'Path:',
    'sources.warning': 'Warning:',
    'sources.fileNotUploaded': 'File was not uploaded to Langflow',
    'sources.rows': 'Rows:',
    'sources.columns': 'Columns',
    'sources.firstRows': 'First rows:',
    'sources.size': 'Size:',
    'sources.connectedTables': 'Connected tables:',
    'sources.tablesNotFound': 'Tables not found:',
    'sources.removeFile': 'Remove',
    'sources.bigQueryInstructions': 'How to get your BigQuery credentials JSON file:',
    'sources.bigQueryStep1': '1. Go to Google Cloud Console',
    'sources.bigQueryStep2': '2. Navigate to APIs & Services > Credentials',
    'sources.bigQueryStep3': '3. Click "Create Credentials" > "Service Account"',
    'sources.bigQueryStep4': '4. Fill in the service account details and click "Create"',
    'sources.bigQueryStep5': '5. Click on the created service account',
    'sources.bigQueryStep6': '6. Go to "Keys" tab and click "Add Key" > "Create new key"',
    'sources.bigQueryStep7': '7. Select "JSON" format and download the file',
    'sources.bigQueryStep8': '8. Upload the downloaded JSON file above',
    'sources.bigQueryDocsLink': 'View official documentation',
    'sources.useExistingCredential': 'Use existing credential',
    'sources.selectCredential': 'Select a credential',
    'sources.savedSourcesAppear': 'Saved sources will appear here',
    'sources.addSourcesInstructions': 'Click Add above to add CSV or XLSX files, connect to BigQuery, or link Google Sheets.',
    
    // Agent
    'agent.title': 'Agent Configuration',
    'agent.name': 'Name',
    'agent.namePlaceholder': 'E.g.: Sales Analysis 2025',
    'agent.selectAgent': 'Select Agent',
    'agent.description': 'Description',
    'agent.descriptionPlaceholder': 'Describe what this agent should do...',
    'agent.dataSource': 'Data Source',
    'agent.selectDataSource': 'Select a data source',
    'agent.sharing': 'Sharing',
    'agent.enableSharing': 'Enable sharing',
    'agent.sharePassword': 'Share password',
    'agent.sharePasswordPlaceholder': 'Leave empty for no password',
    'agent.shareLink': 'Share link',
    'agent.copyLink': 'Copy link',
    'agent.linkCopied': 'Link copied!',
    'agent.suggestedQuestions': 'Suggested Questions',
    'agent.addQuestion': 'Add question',
    'agent.questionPlaceholder': 'Enter a suggested question...',
    'agent.save': 'Save',
    'agent.saving': 'Saving...',
    'agent.delete': 'Delete',
    'agent.deleting': 'Deleting...',
    'agent.deleteConfirm': 'Are you sure you want to delete the agent "{name}"? This action cannot be undone.',
    'agent.deleted': 'Agent deleted',
    'agent.deletedSuccess': 'Agent deleted successfully',
    'agent.error': 'Error',
    'agent.saved': 'Agent saved',
    'agent.savedSuccess': 'Agent saved successfully',
    'agent.createAgent': 'Create Agent',
    'agent.saveChanges': 'Save Changes',
    'agent.newAgent': 'New agent',
    'agent.noDataSourcesFound': 'No data sources found. Add sources first.',
    'agent.selectDataSourceHelp': 'Select the data source that this agent will have access to answer questions.',
    'agent.addSuggestedQuestionsHelp': 'Add questions that will appear as suggestions when someone uses this agent.',
    'agent.enableSharingHelp': 'Allows external people to access this agent',
    'agent.linkCopiedDescription': 'Shareable link copied to clipboard',
    'agent.passwordProtected': 'Password protected access',
    'agent.publicAccess': 'Public access - anyone with the link can access',
    'agent.passwordUpdated': 'Password updated',
    'agent.passwordUpdatedSuccess': 'Share password updated successfully',
    'agent.sharingEnabled': 'Sharing enabled',
    'agent.sharingDisabled': 'Sharing disabled',
    'agent.sharingEnabledSuccess': 'Shareable link created successfully',
    'agent.sharingDisabledSuccess': 'Shareable link removed',
    
     // Questions
     'questions.title': 'Questions',
     'questions.beforeStart': 'Before you start',
     'questions.createAgentFirst': 'Create an agent in "Briefing" to start asking questions.',
     'questions.agent': 'Agent',
     'questions.questionPlaceholder': 'Ex.: What is the revenue for the last 3 months by region?',
     'questions.ask': 'Ask',
     'questions.processing': 'Processing...',
     'questions.error': 'Error:',
     'questions.feedbackError': 'Error saving feedback:',
     'questions.suggestedQuestions': 'Suggested Questions',
     'questions.suggestedQuestionsLabel': 'Suggested Questions',
     'questions.clickToAsk': 'Click to ask',
     'questions.noSessions': 'No questions asked yet.',
     'questions.noQuestionsFound': 'No questions found yet.',
     'questions.processingQuestion': 'Processing your question...',
     'questions.question': 'Question',
     'questions.answerNotAvailable': 'Answer not available',
     'questions.analysisResult': 'Analysis Result',
     'questions.followUpQuestions': 'Follow-up Questions',
     'questions.positiveFeedbackLabel': 'Mark as positive feedback',
     'questions.negativeFeedbackLabel': 'Mark as negative feedback',
     'questions.deleteQuestionLabel': 'Delete question',
     'questions.deleteQuestionConfirm': 'Are you sure you want to delete this question?',
     'questions.status': 'Status',
     'questions.availableColumns': 'Available Columns',
     'questions.warmupQuestions': 'Warmup Questions',
     'questions.clearConversation': 'Clear conversation',
     'questions.seoDescription': 'Ask questions in natural language',
     'questions.dateFormat': 'en-US',
     
     // Agent Settings
     'agentSettings.title': 'Agent Settings',
     'agentSettings.instructions': 'Specific Instructions for the Agent',
     'agentSettings.instructionsPlaceholder': 'Enter specific instructions that the agent should follow when answering questions...',
     'agentSettings.instructionsHelp': 'These instructions will be used by the agent to customize responses.',
     'agentSettings.warmupQuestions': 'Warmup Questions',
     'agentSettings.warmupQuestionsHelp': 'These questions will appear below the available columns to help users get started.',
     'agentSettings.addQuestion': 'Add new warmup question...',
     'agentSettings.cancel': 'Cancel',
     'agentSettings.save': 'Save',
     'agentSettings.saving': 'Saving...',
     'agentSettings.loadError': 'Error loading settings',
     'agentSettings.saveSuccess': 'Settings saved successfully',
     'agentSettings.saveError': 'Error saving settings',
    
    // Alerts
    'alerts.title': 'Alerts',
    'alerts.beforeStart': 'Before you start',
    'alerts.createAgentFirst': 'Create an agent in "Briefing" to start creating alerts.',
    'alerts.agent': 'Agent',
    'alerts.alertName': 'Alert Name',
    'alerts.question': 'Question',
    'alerts.email': 'Email',
    'alerts.emailPlaceholder': 'your@email.com',
    'alerts.frequency': 'Frequency',
    'alerts.daily': 'Daily',
    'alerts.weekly': 'Weekly',
    'alerts.monthly': 'Monthly',
    'alerts.executionTime': 'Execution Time',
    'alerts.dayOfWeek': 'Day of Week',
    'alerts.dayOfMonth': 'Day of Month',
    'alerts.monday': 'Monday',
    'alerts.tuesday': 'Tuesday',
    'alerts.wednesday': 'Wednesday',
    'alerts.thursday': 'Thursday',
    'alerts.friday': 'Friday',
    'alerts.saturday': 'Saturday',
    'alerts.sunday': 'Sunday',
    'alerts.createAlert': 'Create Alert',
    'alerts.creating': 'Creating...',
    'alerts.fillRequiredFields': 'Please fill in all required fields',
    'alerts.success': 'Success',
    'alerts.alertCreated': 'Alert created successfully!',
    'alerts.errorCreatingAlert': 'Error creating alert',
    'alerts.error': 'Error',
    'alerts.noAlerts': 'No alerts configured yet.',
    'alerts.deleteConfirm': 'Are you sure you want to delete this alert?',
    'alerts.deleted': 'Alert deleted',
    'alerts.deletedSuccess': 'Alert deleted successfully',
    'alerts.newAlert': 'New Alert',
    'alerts.alertNameLabel': 'Alert Name',
    'alerts.alertNamePlaceholder': 'Alert name',
    'alerts.agentLabel': 'Agent',
    'alerts.selectAgentPlaceholder': 'Select an agent',
    'alerts.emailLabel': 'Email for notification',
    'alerts.questionLabel': 'Question/Query',
    'alerts.questionPlaceholder': 'What question or condition to monitor?',
    'alerts.frequencyLabel': 'Frequency',
    'alerts.executionTimeLabel': 'Execution Time',
    'alerts.dayOfWeekLabel': 'Day of Week',
    'alerts.dayOfMonthLabel': 'Day of Month',
    'alerts.noAlertsConfigured': 'No alerts configured. Create your first alert above.',
    'alerts.remove': 'Remove',
    'alerts.questionField': 'Question:',
    'alerts.emailField': 'Email:',
    'alerts.scheduleField': 'Schedule:',
    'alerts.at': 'at',
    'alerts.day': 'Day',
    'alerts.createdAt': 'Created at:',
    'alerts.nextExecution': 'Next execution:',
    'alerts.alertRemoved': 'Alert removed',
    
    // Account
    'account.title': 'Account',
    'account.export': 'Export',
    'account.exportHistory': 'Export History',
    'account.security': 'Security',
    'account.deleteAccount': 'Delete Account and Data',
    'account.deleteConfirm': 'Are you sure you want to delete your account and local data?',
    
    // BigQuery Credentials
    'bigquery.addCredential.title': 'Add New BigQuery Credential',
    'bigquery.addCredential.description': 'Upload a new BigQuery service key',
    'bigquery.addCredential.nameLabel': 'Credential Name',
    'bigquery.addCredential.namePlaceholder': 'E.g.: Production, Development, etc.',
    'bigquery.addCredential.fileLabel': 'Credentials File (.json)',
    'bigquery.addCredential.fileSelected': 'Selected file:',
    'bigquery.addCredential.uploadButton': 'Add Credential',
    'bigquery.addCredential.uploading': 'Uploading...',
    'bigquery.configured.title': 'Configured Credentials',
    'bigquery.configured.description': 'Manage your BigQuery credentials',
    'bigquery.configured.loading': 'Loading credentials...',
    'bigquery.configured.empty': 'No credentials configured. Add one above.',
    'bigquery.configured.name': 'Name',
    'bigquery.configured.projectId': 'Project ID',
    'bigquery.configured.langflowPath': 'Langflow Path',
    'bigquery.configured.createdAt': 'Created at',
    'bigquery.configured.actions': 'Actions',
    'bigquery.delete.title': 'Confirm deletion',
    'bigquery.delete.description': 'Are you sure you want to remove the credential "{name}"? This action cannot be undone.',
    'bigquery.delete.cancel': 'Cancel',
    'bigquery.delete.confirm': 'Delete',
    'bigquery.errors.invalidFile': 'Please select a valid JSON file',
    'bigquery.errors.missingFields': 'Please fill in the name and select a file',
    'bigquery.errors.invalidJson': 'Invalid JSON file',
    'bigquery.errors.uploadFailed': 'Error adding credential',
    'bigquery.errors.loadFailed': 'Error loading credentials',
    'bigquery.errors.deleteFailed': 'Error removing credential',
    'bigquery.success.added': 'Credential added successfully!',
    'bigquery.success.deleted': 'Credential removed successfully',
    
    // Footer
    'footer.copyright': '© {year} Talk to your data. All rights reserved.',
    
         // Channels
     'channels.title': 'Channels',
     'channels.subtitle': 'Connect and manage your communication channels to streamline customer interactions',
     'channels.whatsapp.name': 'WhatsApp',
     'channels.whatsapp.description': 'Connect your WhatsApp Business API to receive and respond to messages',
     'channels.slack.name': 'Slack',
     'channels.slack.description': 'Integrate with Slack to manage conversations and notifications',
     'channels.telegram.name': 'Telegram',
     'channels.telegram.description': 'Connect Telegram bot for automated customer support',
     'channels.comingSoon': 'Coming Soon',
     'channels.available': 'Available',
     'channels.connectWhatsApp': 'Connect WhatsApp',
     'channels.connectSlack': 'Connect Slack',
     'channels.connectTelegram': 'Connect Telegram',
     'channels.connecting': 'Connecting...',
     'channels.connected': 'Connected',
     'channels.needMoreIntegrations.title': 'Need More Integrations?',
     'channels.needMoreIntegrations.description': 'We\'re constantly adding new channel integrations. Contact our support team to request specific platforms.',
     'channels.requestIntegration': 'Request Integration',
     
     // Pricing
     'pricing.title': 'Pricing',
     'pricing.subtitle': 'Choose the plan that best fits your needs',
           'pricing.free.title': 'Free',
      'pricing.free.price': '$0',
      'pricing.free.period': '/month',
      'pricing.free.description': 'Perfect for getting started',
      'pricing.free.button': 'Get Started',
                       'pricing.pro.title': 'Pro',
       'pricing.pro.price': '$199',
       'pricing.pro.period': '/month',
      'pricing.pro.description': 'Ideal for growing teams',
      'pricing.pro.button': 'Start Pro Trial',
           'pricing.enterprise.title': 'Enterprise',
      'pricing.enterprise.price': 'Custom',
      'pricing.enterprise.period': '',
      'pricing.enterprise.description': 'For large organizations',
      'pricing.enterprise.button': 'Contact Sales',
     'pricing.features': 'Features',
     'pricing.mostPopular': 'Most Popular',
     'pricing.billedAnnually': 'Billed annually',
     'pricing.billedMonthly': 'Billed monthly',
     'pricing.save20': 'Save 20%',
     'pricing.needCustom': 'Need something custom?',
     'pricing.contactUs': 'Contact us',
     
      // Account Page Tabs
      'account.tabs.usage': 'Plan Usage',
      'account.tabs.subscription': 'Subscription',
      'account.tabs.sources': 'Data Sources',
      'account.tabs.credentials': 'BigQuery Credentials',
      'account.tabs.users': 'Users',
      'account.tabs.workspaceAccess': 'Workspace Access',
      'account.tabs.settings': 'Settings',
     
     // Add Source Modal
     'addSource.title': 'Add sources',
     'addSource.description': 'Transform your data into intelligent conversations. Connect your data sources and ask questions in natural language to get instant insights.',
     'addSource.examples': 'Supported sources: CSV/Excel files, Google BigQuery databases, and Google Sheets.',
     'addSource.uploadTab': 'Upload',
     'addSource.bigQueryTab': 'BigQuery',
     'addSource.sheetsTab': 'Google Sheets',
     'addSource.uploadTitle': 'Upload sources',
     'addSource.dragDrop': 'Drag and drop or',
     'addSource.chooseFile': 'choose file',
     'addSource.uploadText': 'for upload',
     'addSource.supportedTypes': 'CSV and XLSX',
     'addSource.credentials': 'Credentials (JSON)',
     'addSource.project': 'Project',
     'addSource.dataset': 'Dataset',
     'addSource.allowedTables': 'Allowed tables (comma separated)',
     'addSource.projectPlaceholder': 'my-project',
     'addSource.datasetPlaceholder': 'analytics',
     'addSource.tablesPlaceholder': 'orders, customers',
     'addSource.connectBigQuery': 'Connect BigQuery',
     'addSource.sheetsUrl': 'Google Sheets link',
     'addSource.sheetsUrlPlaceholder': 'https://docs.google.com/spreadsheets/d/...',
     'addSource.sheetsDescription': 'Paste the sharing link of the Google Sheets you want to connect',
     
       // Workspace
       'workspace.chat': 'Chat',
       'workspace.addSourceToStart': 'Add a source to start',
       'workspace.addSourceDescription': 'Upload your data sources to start asking questions and getting insights.',
       'workspace.uploadSource': 'Upload Source',
       'workspace.inputPlaceholder': 'Ask a question about your data...',
       'workspace.addSourceFirst': 'Add a source first to start asking questions',
       'workspace.startConversation': 'Start a conversation',
       'workspace.startConversationDescription': 'Ask questions about your data to get insights and answers.',
      'addSource.connectSheets': 'Connect Google Sheets',
       'addSource.sourceLimit': 'Source limit',
       'addSource.filesUploaded': 'Files uploaded successfully!',
       'addSource.uploadError': 'Error uploading files',
       'workspace.title': 'Workspaces',
       'workspace.createNewWorkspace': 'Create new workspace',
       'workspace.newWorkspace': 'New workspace',
       'workspace.mostRecent': 'Most recent',
       'workspace.oldest': 'Oldest',
       'workspace.nameAZ': 'Name (A-Z)',
       'workspace.sources': 'sources',
       'workspace.source': 'source',
       'workspace.rename': 'Rename',
       'workspace.renameWorkspace': 'Rename workspace',
       'workspace.renameDescription': 'Enter the new name for the workspace',
       'workspace.name': 'Name',
       'workspace.cancel': 'Cancel',
       'workspace.delete': 'Delete',
       'workspace.edit': 'Edit',
       'workspace.description': 'Manage your workspaces',
       'workspace.errorCreatingWorkspace': 'Error creating workspace',
       'workspace.renameSuccess': 'Workspace renamed successfully',
       'workspace.renameError': 'Error renaming workspace',
       'workspace.deleteConfirm': 'Are you sure you want to delete the workspace "{name}"? This action cannot be undone.',
       'workspace.deleteSuccess': 'Workspace deleted successfully',
       'workspace.deleteError': 'Error deleting workspace',
       'workspace.dataPreview': 'Data Preview',
       'workspace.dataPreviewDescription': 'Viewing the first rows of the data source',
       'workspace.noPreviewData': 'No preview data available',
       'workspace.previousConversations': 'Previous Conversations',
       'workspace.previousConversationsDescription': 'Select a conversation to continue from where you left off',
       'workspace.noPreviousConversations': 'No previous conversations found',
       
       // Studio
       'studio.title': 'Studio',
      'studio.audioOverview': 'Audio Overview',
      'studio.autoML': 'Auto ML',
      'studio.reports': 'Reports',
      'studio.alertConfig': 'Alert Configuration',
      'studio.connectWhatsApp': 'Connect to WhatsApp',
      'studio.connectSlack': 'Connect to Slack',
      'studio.connections': 'Connections',
      'studio.outputDescription': 'Studio output will be saved here. After adding sources, click to add Audio Overview, Study Guide, Mind Map and more!',
      'studio.addNote': 'Add note',
      'studio.comingSoon': 'Coming soon',
      'studio.comingSoonDescription': 'This feature will be available soon.',
      
      // Users Management
      'users.title': 'User Management',
      'users.description': 'Manage system users and permissions',
      'users.addUser': 'Add User',
      'users.addUserButton': 'Add User',
      'users.newUser': 'New User',
      'users.inviteNewUser': 'Invite New User',
      'users.inviteDescription': 'Invite a new user to access the system',
      'users.email': 'Email',
      'users.emailPlaceholder': 'user@example.com',
      'users.role': 'Role',
      'users.profile': 'Profile',
      'users.admin': 'Administrator',
      'users.member': 'Member',
      'users.createdAt': 'Created',
      'users.actions': 'Actions',
      'users.cancel': 'Cancel',
      'users.add': 'Add',
      'users.adding': 'Adding...',
      'users.addSuccess': 'User added successfully',
      'users.addError': 'Error adding user:',
      'users.emailAlreadyExists': 'This email is already registered in the system',
      'users.removeSuccess': 'User removed successfully',
      'users.removeError': 'Error removing user:',
      'users.noUsersFound': 'No users found',
      'users.validEmailError': 'Enter a valid email',
      'users.systemUsers': 'System Users',
      'users.inviteSuccess': 'User invited successfully! They will receive an email to set their password.',
      
      // Workspace Access Management
      'workspaceAccess.title': 'Workspace Access Control',
      'workspaceAccess.description': 'Manage user access to workspaces',
      'workspaceAccess.grantAccess': 'Grant Access',
      'workspaceAccess.grantAccessDescription': 'Allow users to access specific workspaces',
      'workspaceAccess.selectWorkspace': 'Select a workspace',
      'workspaceAccess.selectUser': 'Select a user',
      'workspaceAccess.grant': 'Grant',
      'workspaceAccess.grantedAccess': 'Granted Access',
      'workspaceAccess.grantedAccessDescription': 'List of users with access to each workspace',
      'workspaceAccess.workspace': 'Workspace',
      'workspaceAccess.user': 'User',
      'workspaceAccess.grantedAt': 'Granted Date',
      'workspaceAccess.actions': 'Actions',
      'workspaceAccess.noAccessGranted': 'No access granted',
      'workspaceAccess.selectWorkspaceAndUser': 'Select a workspace and a user',
      'workspaceAccess.accessGrantedSuccess': 'Access granted successfully',
      'workspaceAccess.accessGrantedError': 'Error granting access:',
      'workspaceAccess.accessRevokedSuccess': 'Access revoked successfully',
      'workspaceAccess.accessRevokedError': 'Error revoking access:',
   },
  pt: {
    // Common
    'common.loading': 'Carregando...',
    
    // Navigation
    'nav.dashboard': 'Painel',
    'nav.account': 'Conta',
    'nav.logout': 'Sair',
    'nav.getStarted': 'Começar agora',
    'nav.tagline': 'Converse com seus dados',
    
    // Hero Section
    'hero.title': 'Transforme seus dados em conversas inteligentes',
    'hero.subtitle': 'Conecte suas fontes de dados e faça perguntas em linguagem natural. Obtenha insights instantâneos sem consultas complexas.',
    'hero.getStarted': 'Começar agora',
    'hero.howItWorks': 'Como funciona',
    
    // How it works
    'howItWorks.title': 'Como funciona',
    'howItWorks.step1.title': 'Conecte seus dados',
    'howItWorks.step1.description': 'Carregue arquivos CSV, conecte ao BigQuery ou adicione outras fontes de dados',
    'howItWorks.step2.title': 'Faça perguntas',
    'howItWorks.step2.description': 'Use linguagem natural para consultar seus dados',
    'howItWorks.step3.title': 'Obtenha insights',
    'howItWorks.step3.description': 'Receba respostas instantâneas com gráficos e visualizações',
    'howItWorks.step4.title': 'Alertas',
    'howItWorks.step4.description': 'Crie alertas para monitorar métricas e receber notificações',
    
    // Benefits
    'benefits.title': 'Benefícios',
    'benefits.easy.title': 'Fácil de usar',
    'benefits.easy.description': 'Não é necessário aprender SQL ou linguagens de consulta complexas',
    'benefits.easy.extended': 'Faça perguntas em linguagem natural e obtenha insights sem precisar escrever consultas complexas.',
    'benefits.easy.tagline': 'Análise de dados simplificada.',
    'benefits.fast.title': 'Insights rápidos',
    'benefits.fast.description': 'Obtenha respostas em segundos, não em horas',
    'benefits.fast.extended': 'Conecte suas fontes de dados e comece a fazer perguntas imediatamente para obter respostas instantâneas.',
    'benefits.fast.tagline': 'Tome decisões com agilidade.',
    'benefits.secure.title': 'Seguro',
    'benefits.secure.description': 'Seus dados permanecem privados e seguros',
    'benefits.secure.extended': 'Seus dados são criptografados e você mantém total controle sobre quem pode acessá-los.',
    'benefits.secure.tagline': 'Privacidade garantida.',
    
    // Testimonials
    'testimonials.title': 'O que as pessoas estão dizendo',
    'testimonials.feedback1': 'Finalmente uma ferramenta que entende que eu não falo SQL. Só pergunto em português mesmo e ela me responde. Incrível!',
    'testimonials.name1': 'João Developer',
    'testimonials.role1': 'Ex-escravo de Excel',
    'testimonials.feedback2': 'Economizei horas tentando entender dashboards complexos. Agora só pergunto "quanto vendemos esse mês?" e pronto.',
    'testimonials.name2': 'Maria Silva',
    'testimonials.role2': 'CEO de Alguma Coisa',
    'testimonials.feedback3': 'Conectei meu BigQuery e agora converso com bilhões de linhas como se fosse um chat. Meus relatórios saem em segundos.',
    'testimonials.name3': 'Pedro Costa',
    'testimonials.role3': 'Fundador de Startup Unicórnio',
    
    // Auth
    'auth.title': 'Acessar sua conta',
    'auth.login': 'Login',
    'auth.register': 'Registrar',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.name': 'Nome',
    'auth.loginButton': 'Entrar',
    'auth.registerButton': 'Criar conta',
    'auth.loginError': 'Falha ao entrar. Tente novamente.',
    'auth.registerError': 'Falha ao registrar. Tente novamente.',
    'auth.registerSuccess': 'Cadastro realizado! Verifique seu e-mail para confirmar e então faça login.',
    'auth.forgotPassword': 'Esqueceu a senha?',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.dataSources': 'Fontes de Dados',
    'dashboard.connectedSources': 'fonte(s) conectada(s)',
    'dashboard.addSource': 'Configurar Fontes',
    'dashboard.agentConfig': 'Configuração do Agente',
    'dashboard.agentConfigDesc': 'Adicione o detalhamento das fontes para o agente entender o contexto.',
    'dashboard.configureAgent': 'Configurar Agente',
    'dashboard.questionsAnswers': 'Perguntas & Respostas',
    'dashboard.activeAgents': 'agente(s) ativo(s)',
    'dashboard.newQuestion': 'Nova Pergunta',
    'dashboard.alerts': 'Alertas',
    'dashboard.configuredAlerts': 'alerta(s) configurado(s)',
    'dashboard.createAlert': 'Criar Alerta',
    'dashboard.channelConfig': 'Configuração de Canais',
    'dashboard.channelConfigDesc': 'Configure em quais canais seus agentes estarão disponíveis.',
    'dashboard.configureChannels': 'Configurar Canais',
    'dashboard.dataExplore': 'Exploração de Dados',
    'dashboard.dataExploreDesc': 'Explore e analise seus dados com visualizações interativas e insights.',
    'dashboard.autoML': 'Auto ML',
    'dashboard.autoMLDesc': 'Construa e implante automaticamente modelos de machine learning a partir dos seus dados.',
    'dashboard.comingSoon': 'Em Breve',
    
    // Sources
    'sources.title': 'Fontes',
    'sources.add': 'Adicionar',
    'sources.filesTab': 'Arquivos (CSV/XLSX)',
    'sources.bigQueryTab': 'Google BigQuery',
    'sources.uploadButton': 'Fazer upload',
    'sources.uploading': 'Enviando...',
    'sources.connectBigQuery': 'Conectar BigQuery',
    'sources.connecting': 'Conectando...',
    'sources.credentials': 'Credenciais (JSON)',
    'sources.project': 'Projeto',
    'sources.dataset': 'Dataset',
    'sources.allowedTables': 'Tabelas permitidas (separadas por vírgula)',
    'sources.projectPlaceholder': 'meu-projeto',
    'sources.datasetPlaceholder': 'analytics',
    'sources.tablesPlaceholder': 'orders, customers',
    'sources.noSourcesFound': 'Nenhuma fonte de dados encontrada. Faça upload de arquivos CSV ou XLSX acima.',
    'sources.deleteConfirm': 'Tem certeza que deseja deletar esta fonte de dados?',
    'sources.uploadError': 'Erro no upload:',
    'sources.selectCredentialsFile': 'Por favor, selecione o arquivo de credenciais JSON',
    'sources.fillRequiredFields': 'Por favor, preencha todos os campos obrigatórios',
    'sources.bigQueryConnected': 'BigQuery conectado com sucesso! Fonte:',
    'sources.bigQueryError': 'Erro ao conectar BigQuery:',
    'sources.unknownError': 'Erro desconhecido',
    'sources.createdAt': 'Criado em:',
    'sources.langflowIntegration': 'Integração Langflow',
    'sources.langflowName': 'Nome no Langflow:',
    'sources.langflowPath': 'Caminho:',
    'sources.warning': 'Aviso:',
    'sources.fileNotUploaded': 'Arquivo não foi carregado no Langflow',
    'sources.rows': 'Linhas:',
    'sources.columns': 'Colunas',
    'sources.firstRows': 'Primeiras linhas:',
    'sources.size': 'Tamanho:',
    'sources.connectedTables': 'Tabelas conectadas:',
    'sources.tablesNotFound': 'Tabelas não encontradas:',
    'sources.removeFile': 'Remover',
    'sources.bigQueryInstructions': 'Como obter seu arquivo JSON de credenciais do BigQuery:',
    'sources.bigQueryStep1': '1. Acesse o Google Cloud Console',
    'sources.bigQueryStep2': '2. Navegue para APIs e Serviços > Credenciais',
    'sources.bigQueryStep3': '3. Clique em "Criar Credenciais" > "Conta de Serviço"',
    'sources.bigQueryStep4': '4. Preencha os detalhes da conta de serviço e clique em "Criar"',
    'sources.bigQueryStep5': '5. Clique na conta de serviço criada',
    'sources.bigQueryStep6': '6. Vá para a aba "Chaves" e clique em "Adicionar Chave" > "Criar nova chave"',
    'sources.bigQueryStep7': '7. Selecione o formato "JSON" e baixe o arquivo',
    'sources.bigQueryStep8': '8. Faça upload do arquivo JSON baixado acima',
    'sources.bigQueryDocsLink': 'Ver documentação oficial',
    'sources.useExistingCredential': 'Usar credencial existente',
    'sources.selectCredential': 'Selecione uma credencial',
    'sources.savedSourcesAppear': 'As fontes salvas aparecerão aqui',
    'sources.addSourcesInstructions': 'Clique em Adicionar acima para adicionar arquivos CSV ou XLSX, conectar ao BigQuery ou vincular Google Sheets.',
    
    // Agent
    'agent.title': 'Configuração do Agente',
    'agent.name': 'Nome',
    'agent.namePlaceholder': 'Ex.: Análises de Vendas 2025',
    'agent.selectAgent': 'Selecionar Agente',
    'agent.description': 'Descrição',
    'agent.descriptionPlaceholder': 'Descreva o que este agente deve fazer...',
    'agent.dataSource': 'Fonte de Dados',
    'agent.selectDataSource': 'Selecione uma fonte de dados',
    'agent.sharing': 'Compartilhamento',
    'agent.enableSharing': 'Habilitar compartilhamento',
    'agent.sharePassword': 'Senha de compartilhamento',
    'agent.sharePasswordPlaceholder': 'Deixe vazio para sem senha',
    'agent.shareLink': 'Link de compartilhamento',
    'agent.copyLink': 'Copiar link',
    'agent.linkCopied': 'Link copiado!',
    'agent.suggestedQuestions': 'Perguntas Sugeridas',
    'agent.addQuestion': 'Adicionar pergunta',
    'agent.questionPlaceholder': 'Digite uma pergunta sugerida...',
    'agent.save': 'Salvar',
    'agent.saving': 'Salvando...',
    'agent.delete': 'Deletar',
    'agent.deleting': 'Deletando...',
    'agent.deleteConfirm': 'Tem certeza que deseja deletar o agente "{name}"? Esta ação não pode ser desfeita.',
    'agent.deleted': 'Agente deletado',
    'agent.deletedSuccess': 'Agente deletado com sucesso',
    'agent.error': 'Erro',
    'agent.saved': 'Agente salvo',
    'agent.savedSuccess': 'Agente salvo com sucesso',
    'agent.createAgent': 'Criar Agente',
    'agent.saveChanges': 'Salvar Alterações',
    'agent.newAgent': 'Novo agente',
    'agent.noDataSourcesFound': 'Nenhuma fonte de dados encontrada. Adicione fontes primeiro.',
    'agent.selectDataSourceHelp': 'Selecione a fonte de dados que este agente terá acesso para responder perguntas.',
    'agent.addSuggestedQuestionsHelp': 'Adicione perguntas que aparecerão como sugestões quando alguém usar este agente.',
    'agent.enableSharingHelp': 'Permite que pessoas externas acessem este agente',
    'agent.linkCopiedDescription': 'Link compartilhável copiado para a área de transferência',
    'agent.passwordProtected': 'Acesso protegido por senha',
    'agent.publicAccess': 'Acesso público - qualquer pessoa com o link pode acessar',
    'agent.passwordUpdated': 'Senha atualizada',
    'agent.passwordUpdatedSuccess': 'Senha de compartilhamento atualizada com sucesso',
    'agent.sharingEnabled': 'Compartilhamento ativado',
    'agent.sharingDisabled': 'Compartilhamento desativado',
    'agent.sharingEnabledSuccess': 'Link compartilhável criado com sucesso',
    'agent.sharingDisabledSuccess': 'Link compartilhável removido',
    
    // Questions
    'questions.title': 'Perguntas',
    'questions.beforeStart': 'Antes de começar',
    'questions.createAgentFirst': 'Crie um agente em "Briefing" para começar a perguntar.',
    'questions.agent': 'Agente',
    'questions.questionPlaceholder': 'Ex.: Qual a receita dos últimos 3 meses por região?',
    'questions.ask': 'Perguntar',
    'questions.processing': 'Processando...',
    'questions.error': 'Erro:',
    'questions.feedbackError': 'Erro ao salvar feedback:',
    'questions.suggestedQuestions': 'Perguntas Sugeridas',
    'questions.suggestedQuestionsLabel': 'Perguntas Sugeridas',
    'questions.clickToAsk': 'Clique para perguntar',
    'questions.noSessions': 'Nenhuma pergunta feita ainda.',
    'questions.noQuestionsFound': 'Nenhuma pergunta encontrada ainda.',
    'questions.processingQuestion': 'Processando sua pergunta...',
    'questions.question': 'Pergunta',
    'questions.answerNotAvailable': 'Resposta não disponível',
    'questions.analysisResult': 'Resultado da Análise',
    'questions.followUpQuestions': 'Perguntas de Acompanhamento',
    'questions.positiveFeedbackLabel': 'Marcar como feedback positivo',
    'questions.negativeFeedbackLabel': 'Marcar como feedback negativo',
    'questions.deleteQuestionLabel': 'Deletar pergunta',
    'questions.deleteQuestionConfirm': 'Tem certeza que deseja deletar esta pergunta?',
     'questions.status': 'Status',
     'questions.availableColumns': 'Colunas disponíveis',
     'questions.warmupQuestions': 'Perguntas de Aquecimento',
     'questions.clearConversation': 'Limpar conversa',
     'questions.seoDescription': 'Faça perguntas em linguagem natural',
     'questions.dateFormat': 'pt-BR',
     
     // Agent Settings
     'agentSettings.title': 'Configurações do Agente',
     'agentSettings.instructions': 'Orientações Específicas para o Agente',
     'agentSettings.instructionsPlaceholder': 'Digite as orientações específicas que o agente deve seguir ao responder perguntas...',
     'agentSettings.instructionsHelp': 'Essas orientações serão usadas pelo agente para personalizar as respostas.',
     'agentSettings.warmupQuestions': 'Perguntas de Aquecimento',
     'agentSettings.warmupQuestionsHelp': 'Essas perguntas aparecerão abaixo das colunas disponíveis para ajudar os usuários a começar.',
     'agentSettings.addQuestion': 'Digite uma nova pergunta de aquecimento...',
     'agentSettings.cancel': 'Cancelar',
     'agentSettings.save': 'Salvar',
     'agentSettings.saving': 'Salvando...',
     'agentSettings.loadError': 'Erro ao carregar configurações',
     'agentSettings.saveSuccess': 'Configurações salvas com sucesso',
     'agentSettings.saveError': 'Erro ao salvar configurações',
     
     // Alerts
    'alerts.title': 'Alertas',
    'alerts.beforeStart': 'Antes de começar',
    'alerts.createAgentFirst': 'Crie um agente em "Briefing" para começar a criar alertas.',
    'alerts.agent': 'Agente',
    'alerts.alertName': 'Nome do Alerta',
    'alerts.question': 'Pergunta',
    'alerts.email': 'E-mail',
    'alerts.emailPlaceholder': 'seu@email.com',
    'alerts.frequency': 'Frequência',
    'alerts.daily': 'Diário',
    'alerts.weekly': 'Semanal',
    'alerts.monthly': 'Mensal',
    'alerts.executionTime': 'Horário de Execução',
    'alerts.dayOfWeek': 'Dia da Semana',
    'alerts.dayOfMonth': 'Dia do Mês',
    'alerts.monday': 'Segunda-feira',
    'alerts.tuesday': 'Terça-feira',
    'alerts.wednesday': 'Quarta-feira',
    'alerts.thursday': 'Quinta-feira',
    'alerts.friday': 'Sexta-feira',
    'alerts.saturday': 'Sábado',
    'alerts.sunday': 'Domingo',
    'alerts.createAlert': 'Criar Alerta',
    'alerts.creating': 'Criando...',
    'alerts.fillRequiredFields': 'Preencha todos os campos obrigatórios',
    'alerts.success': 'Sucesso',
    'alerts.alertCreated': 'Alerta criado com sucesso!',
    'alerts.errorCreatingAlert': 'Erro ao criar alerta',
    'alerts.error': 'Erro',
    'alerts.noAlerts': 'Nenhum alerta configurado ainda.',
    'alerts.deleteConfirm': 'Tem certeza que deseja deletar este alerta?',
    'alerts.deleted': 'Alerta deletado',
    'alerts.deletedSuccess': 'Alerta deletado com sucesso',
    'alerts.newAlert': 'Novo Alerta',
    'alerts.alertNameLabel': 'Nome do Alerta',
    'alerts.alertNamePlaceholder': 'Nome do alerta',
    'alerts.agentLabel': 'Agente',
    'alerts.selectAgentPlaceholder': 'Selecione um agente',
    'alerts.emailLabel': 'E-mail para notificação',
    'alerts.questionLabel': 'Pergunta/Query',
    'alerts.questionPlaceholder': 'Qual pergunta ou condição monitorar?',
    'alerts.frequencyLabel': 'Frequência',
    'alerts.executionTimeLabel': 'Horário de Execução',
    'alerts.dayOfWeekLabel': 'Dia da Semana',
    'alerts.dayOfMonthLabel': 'Dia do Mês',
    'alerts.noAlertsConfigured': 'Nenhum alerta configurado. Crie seu primeiro alerta acima.',
    'alerts.remove': 'Remover',
    'alerts.questionField': 'Pergunta:',
    'alerts.emailField': 'Email:',
    'alerts.scheduleField': 'Agendamento:',
    'alerts.at': 'às',
    'alerts.day': 'Dia',
    'alerts.createdAt': 'Criado em:',
    'alerts.nextExecution': 'Próxima execução:',
    'alerts.alertRemoved': 'Alerta removido',
    
    // Account
    'account.title': 'Conta',
    'account.export': 'Exportação',
    'account.exportHistory': 'Exportar histórico',
    'account.security': 'Segurança',
    'account.deleteAccount': 'Excluir conta e dados',
    'account.deleteConfirm': 'Tem certeza que deseja excluir sua conta e dados locais?',
    
    // BigQuery Credentials
    'bigquery.addCredential.title': 'Adicionar Nova Credencial BigQuery',
    'bigquery.addCredential.description': 'Faça upload de uma nova chave de serviço do BigQuery',
    'bigquery.addCredential.nameLabel': 'Nome da Credencial',
    'bigquery.addCredential.namePlaceholder': 'Ex: Produção, Desenvolvimento, etc.',
    'bigquery.addCredential.fileLabel': 'Arquivo de Credenciais (.json)',
    'bigquery.addCredential.fileSelected': 'Arquivo selecionado:',
    'bigquery.addCredential.uploadButton': 'Adicionar Credencial',
    'bigquery.addCredential.uploading': 'Enviando...',
    'bigquery.configured.title': 'Credenciais Configuradas',
    'bigquery.configured.description': 'Gerencie suas credenciais do BigQuery',
    'bigquery.configured.loading': 'Carregando credenciais...',
    'bigquery.configured.empty': 'Nenhuma credencial configurada. Adicione uma acima.',
    'bigquery.configured.name': 'Nome',
    'bigquery.configured.projectId': 'Project ID',
    'bigquery.configured.langflowPath': 'Caminho Langflow',
    'bigquery.configured.createdAt': 'Criado em',
    'bigquery.configured.actions': 'Ações',
    'bigquery.delete.title': 'Confirmar exclusão',
    'bigquery.delete.description': 'Tem certeza que deseja remover a credencial "{name}"? Esta ação não pode ser desfeita.',
    'bigquery.delete.cancel': 'Cancelar',
    'bigquery.delete.confirm': 'Excluir',
    'bigquery.errors.invalidFile': 'Por favor, selecione um arquivo JSON válido',
    'bigquery.errors.missingFields': 'Por favor, preencha o nome e selecione um arquivo',
    'bigquery.errors.invalidJson': 'Arquivo JSON inválido',
    'bigquery.errors.uploadFailed': 'Erro ao adicionar credencial',
    'bigquery.errors.loadFailed': 'Erro ao carregar credenciais',
    'bigquery.errors.deleteFailed': 'Erro ao remover credencial',
    'bigquery.success.added': 'Credencial adicionada com sucesso!',
    'bigquery.success.deleted': 'Credencial removida com sucesso',
    
    // Footer
    'footer.copyright': '© {year} Converse com seus dados. Todos os direitos reservados.',
    
         // Channels
     'channels.title': 'Canais',
     'channels.subtitle': 'Conecte e gerencie seus canais de comunicação para otimizar as interações com clientes',
     'channels.whatsapp.name': 'WhatsApp',
     'channels.whatsapp.description': 'Conecte sua API do WhatsApp Business para receber e responder mensagens',
     'channels.slack.name': 'Slack',
     'channels.slack.description': 'Integre com o Slack para gerenciar conversas e notificações',
     'channels.telegram.name': 'Telegram',
     'channels.telegram.description': 'Conecte bot do Telegram para suporte automatizado ao cliente',
     'channels.comingSoon': 'Em Breve',
     'channels.available': 'Disponível',
     'channels.connectWhatsApp': 'Conectar WhatsApp',
     'channels.connectSlack': 'Conectar Slack',
     'channels.connectTelegram': 'Conectar Telegram',
     'channels.connecting': 'Conectando...',
     'channels.connected': 'Conectado',
     'channels.needMoreIntegrations.title': 'Precisa de Mais Integrações?',
     'channels.needMoreIntegrations.description': 'Estamos constantemente adicionando novas integrações de canais. Entre em contato com nossa equipe de suporte para solicitar plataformas específicas.',
     'channels.requestIntegration': 'Solicitar Integração',
     
     // Pricing
     'pricing.title': 'Preços',
     'pricing.subtitle': 'Escolha o plano que melhor atende às suas necessidades',
           'pricing.free.title': 'Grátis',
      'pricing.free.price': 'R$0',
      'pricing.free.period': '/mês',
      'pricing.free.description': 'Perfeito para começar',
      'pricing.free.button': 'Começar Agora',
                       'pricing.pro.title': 'Pro',
       'pricing.pro.price': 'R$199',
       'pricing.pro.period': '/mês',
      'pricing.pro.description': 'Ideal para equipes em crescimento',
      'pricing.pro.button': 'Iniciar Teste Pro',
           'pricing.enterprise.title': 'Empresarial',
      'pricing.enterprise.price': 'Personalizado',
      'pricing.enterprise.period': '',
      'pricing.enterprise.description': 'Para grandes organizações',
      'pricing.enterprise.button': 'Falar com Vendas',
     'pricing.features': 'Recursos',
     'pricing.mostPopular': 'Mais Popular',
     'pricing.billedAnnually': 'Cobrado anualmente',
     'pricing.billedMonthly': 'Cobrado mensalmente',
     'pricing.save20': 'Economize 20%',
     'pricing.needCustom': 'Precisa de algo personalizado?',
     'pricing.contactUs': 'Entre em contato conosco',
     
     // Settings
     'settings.title': 'Configurações',
     'settings.subscription': 'Gerenciar assinatura',
     'settings.users': 'Usuários',
     'settings.workspaceAccess': 'Controle de Acesso',
     'settings.language': 'Idioma',
     'settings.logout': 'Sair',
     'settings.newWorkspace': 'Novo workspace',
      
      // Account Page Tabs
      'account.tabs.usage': 'Uso do Plano',
      'account.tabs.subscription': 'Assinatura',
      'account.tabs.sources': 'Fontes de Dados',
      'account.tabs.credentials': 'Credenciais BigQuery',
      'account.tabs.users': 'Usuários',
      'account.tabs.workspaceAccess': 'Acesso aos Workspaces',
      'account.tabs.settings': 'Configurações',
     
     // Add Source Modal
     'addSource.title': 'Adicionar fontes',
     'addSource.description': 'Transforme seus dados em conversas inteligentes. Conecte suas fontes de dados e faça perguntas em linguagem natural para obter insights instantâneos.',
     'addSource.examples': 'Fontes suportadas: arquivos CSV/Excel, bancos de dados Google BigQuery e Google Sheets.',
     'addSource.uploadTab': 'Upload',
     'addSource.bigQueryTab': 'BigQuery',
     'addSource.sheetsTab': 'Google Sheets',
     'addSource.uploadTitle': 'Upload de fontes',
     'addSource.dragDrop': 'Arraste e solte ou',
     'addSource.chooseFile': 'escolha arquivo',
     'addSource.uploadText': 'para upload',
     'addSource.supportedTypes': 'CSV and XLSX',
     'addSource.credentials': 'Credenciais (JSON)',
     'addSource.project': 'Projeto',
     'addSource.dataset': 'Dataset',
     'addSource.allowedTables': 'Tabelas permitidas (separadas por vírgula)',
     'addSource.projectPlaceholder': 'meu-projeto',
     'addSource.datasetPlaceholder': 'analytics',
     'addSource.tablesPlaceholder': 'orders, customers',
     'addSource.connectBigQuery': 'Conectar BigQuery',
     'addSource.sheetsUrl': 'Link do Google Sheets',
     'addSource.sheetsUrlPlaceholder': 'https://docs.google.com/spreadsheets/d/...',
     'addSource.sheetsDescription': 'Cole o link de compartilhamento do Google Sheets que você deseja conectar',
     'addSource.connectSheets': 'Conectar Google Sheets',
      'addSource.sourceLimit': 'Limite de fontes',
      'addSource.filesUploaded': 'Arquivos enviados com sucesso!',
      'addSource.uploadError': 'Erro ao enviar arquivos',
      
       // Workspace
       'workspace.chat': 'Chat',
       'workspace.addSourceToStart': 'Adicione uma fonte para começar',
       'workspace.addSourceDescription': 'Carregue suas fontes de dados para começar a fazer perguntas e obter insights.',
       'workspace.uploadSource': 'Carregar Fonte',
       'workspace.inputPlaceholder': 'Faça uma pergunta sobre seus dados...',
       'workspace.addSourceFirst': 'Adicione uma fonte primeiro para fazer perguntas',
       'workspace.startConversation': 'Inicie uma conversa',
       'workspace.startConversationDescription': 'Faça perguntas sobre seus dados para obter insights e respostas.',
       'workspace.title': 'Workspaces',
       'workspace.createNewWorkspace': 'Criar novo workspace',
       'workspace.newWorkspace': 'Novo workspace',
       'workspace.mostRecent': 'Mais recentes',
       'workspace.oldest': 'Mais antigos',
       'workspace.nameAZ': 'Nome (A-Z)',
       'workspace.sources': 'fontes',
       'workspace.source': 'fonte',
       'workspace.rename': 'Renomear',
       'workspace.renameWorkspace': 'Renomear workspace',
       'workspace.renameDescription': 'Digite o novo nome para o workspace',
       'workspace.name': 'Nome',
       'workspace.cancel': 'Cancelar',
       'workspace.delete': 'Excluir',
       'workspace.edit': 'Editar',
       'workspace.description': 'Gerencie seus workspaces',
       'workspace.errorCreatingWorkspace': 'Erro ao criar workspace',
       'workspace.renameSuccess': 'Workspace renomeado com sucesso',
       'workspace.renameError': 'Erro ao renomear workspace',
       'workspace.deleteConfirm': 'Tem certeza que deseja excluir o workspace "{name}"? Esta ação não pode ser desfeita.',
       'workspace.deleteSuccess': 'Workspace excluído com sucesso',
       'workspace.deleteError': 'Erro ao excluir workspace',
       'workspace.dataPreview': 'Preview dos Dados',
       'workspace.dataPreviewDescription': 'Visualização das primeiras linhas da fonte de dados',
       'workspace.noPreviewData': 'Nenhum dado de preview disponível',
       'workspace.previousConversations': 'Conversas Anteriores',
       'workspace.previousConversationsDescription': 'Selecione uma conversa para continuar de onde parou',
       'workspace.noPreviousConversations': 'Nenhuma conversa anterior encontrada',
       
      // Studio
      'studio.title': 'Studio',
      'studio.audioOverview': 'Visão Geral de Áudio',
      'studio.autoML': 'Auto ML',
      'studio.reports': 'Relatórios',
      'studio.alertConfig': 'Configuração de Alertas',
      'studio.connectWhatsApp': 'Conectar ao WhatsApp',
      'studio.connectSlack': 'Conectar ao Slack',
      'studio.connections': 'Conexões',
      'studio.outputDescription': 'A saída do Studio será salva aqui. Após adicionar fontes, clique para adicionar Visão Geral de Áudio, Guia de Estudo, Mapa Mental e mais!',
      'studio.addNote': 'Adicionar nota',
      'studio.comingSoon': 'Recurso em breve',
       'studio.comingSoonDescription': 'Esta funcionalidade estará disponível em breve.',
       
       // Users Management
       'users.title': 'Gestão de Usuários',
        'users.description': 'Gerencie os usuários e suas permissões de acesso',
        'users.addUser': 'Adicionar Usuário',
        'users.addUserButton': 'Adicionar Usuário',
        'users.newUser': 'Novo Usuário',
        'users.inviteNewUser': 'Convidar Novo Usuário',
        'users.inviteDescription': 'Um email será enviado ao usuário com instruções para definir sua senha e acessar o sistema.',
        'users.email': 'Email',
        'users.emailPlaceholder': 'usuario@exemplo.com',
        'users.role': 'Perfil',
        'users.profile': 'Perfil',
        'users.admin': 'Administrador',
        'users.member': 'Membro',
        'users.createdAt': 'Data de Criação',
        'users.actions': 'Ações',
        'users.cancel': 'Cancelar',
        'users.add': 'Adicionar',
        'users.adding': 'Adicionando...',
        'users.inviteSuccess': 'Usuário convidado com sucesso! Ele receberá um email para definir sua senha.',
        'users.addSuccess': 'Usuário adicionado com sucesso',
        'users.addError': 'Erro ao adicionar usuário:',
        'users.emailAlreadyExists': 'Este email já está registrado no sistema',
        'users.removeSuccess': 'Usuário removido com sucesso',
        'users.removeError': 'Erro ao remover usuário:',
        'users.noUsersFound': 'Nenhum usuário encontrado',
        'users.validEmailError': 'Digite um email válido',
        'users.systemUsers': 'Usuários do Sistema',
       
       // Workspace Access Management
       'workspaceAccess.title': 'Controle de Acesso aos Workspaces',
       'workspaceAccess.description': 'Gerencie o acesso dos usuários aos workspaces',
       'workspaceAccess.grantAccess': 'Conceder Acesso',
       'workspaceAccess.grantAccessDescription': 'Permita que usuários acessem workspaces específicos',
       'workspaceAccess.selectWorkspace': 'Selecione um workspace',
       'workspaceAccess.selectUser': 'Selecione um usuário',
       'workspaceAccess.grant': 'Conceder',
       'workspaceAccess.grantedAccess': 'Acessos Concedidos',
       'workspaceAccess.grantedAccessDescription': 'Lista de usuários com acesso a cada workspace',
       'workspaceAccess.workspace': 'Workspace',
       'workspaceAccess.user': 'Usuário',
       'workspaceAccess.grantedAt': 'Data de Concessão',
       'workspaceAccess.actions': 'Ações',
       'workspaceAccess.noAccessGranted': 'Nenhum acesso concedido',
       'workspaceAccess.selectWorkspaceAndUser': 'Selecione um workspace e um usuário',
       'workspaceAccess.accessGrantedSuccess': 'Acesso concedido com sucesso',
       'workspaceAccess.accessGrantedError': 'Erro ao conceder acesso:',
       'workspaceAccess.accessRevokedSuccess': 'Acesso revogado com sucesso',
       'workspaceAccess.accessRevokedError': 'Erro ao revogar acesso:',
    }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Try to get the saved language from localStorage
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage && (savedLanguage === 'en' || savedLanguage === 'pt') ? savedLanguage : 'en';
  });

  const t = (key: string, params?: Record<string, any>): string => {
    let text = translations[language][key] || key;
    
    if (params) {
      Object.entries(params).forEach(([param, value]) => {
        text = text.replace(new RegExp(`{${param}}`, 'g'), String(value));
      });
    }
    
    return text;
  };

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};