// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooimkdueuozjfwadrkkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vaW1rZHVldW96amZ3YWRya2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDU5MTIsImV4cCI6MjA3MDU4MTkxMn0.SAADBflVutyfV_XDJTrPlpwoHE8yqdJ_GkLp9Tt_ras";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});